version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: heartify
    ports:
      - "3306:3306"
    hostname: mysql
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app:
      image: heartify/01:latest
      container_name: spring-container
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/heartify
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root
volumes:
  mysql-data: